#!/bin/sh

cd `dirname $0` 

. ./utility_and_settings.sh


fn_grouped_by_type()
{
  awk 'NR==1{old = $2; next}{ print $3 "\t" $2 - old; old= $2}' | awk '!/^start/ {arr[$1]+=$2}END{for (a in arr) print a, int(arr[a]/3600)":"int(arr[a]/60)%60":"arr[a]%60}'
}

fn_get_all_time_from_last_start()
{
  awk '/^start/ { t = $0 "\n"; next } { t = t $0 "\n"; } END { printf "%s", t; }'
}

fn_get_all_time_from_timestamp()
{
  awk -v vmt=$1 '$2>=vmt'
}



fn_stats()
{
  ret=`cat $awl_file_log`
  if [[ $d == true ]]; then
    ret=`echo -e "$ret"|fn_get_all_time_from_timestamp $(fn_get_vmidnight_timestamp)`
  fi
  if [[ $s == true ]]; then
    ret=`echo -e "$ret"|fn_get_all_time_from_last_start`
  fi
  if [[ $g == true ]]; then
    ret=`echo -e "$ret"|fn_grouped_by_type`
  fi
  echo -e "$ret"
}

PARSED_OPTIONS=`getopt -n "$0" -o ":gsd" --long "grouped,from_start,today" -- "$@"`
eval set -- "$PARSED_OPTIONS"

while true; 
do
  case "$1" in
    -g|--grouped)
      g=true
      shift
      ;;
    -s|--from_start)
      s=true
      shift
      ;;
    -d|--today)
      d=true
      shift
      ;;
    --)
      shift
      break;;
  esac
done

if [ "$1" == "start" ]; then
  if [ ! -f $pidfile ]; then
    ./awl_daemon.sh &
    echo $! > $pidfile
    echo "AWL started"
  else
    echo "AWL is already running"
  fi
elif [ "$1" == "stop" ]; then
  if [ -f $pidfile ]; then
    kill `cat $pidfile`
    echo "AWL stopped"
    rm $pidfile
  else
    echo "No AWL istances found"
  fi
elif [ "$1" == "stats" ]; then
  fn_stats $@
else
  echo -e "Available command:\nstart\nstop\nstats"
fi


